name: Build Wasil App AAB & APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force

    - name: Build with buildozer-action
      id: buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: stable

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Wasil-Release-App
        path: ${{ steps.buildozer.outputs.filename }}
